flaskbook/apps/detector/models.py
from datetime import datetime

from apps.app import db

class UserImage(db.Model):
    __tablename__ = "user_images"
    id = db.Column(db.Integer, primary_key=True)
    
    user_id = db.Column(db.String, db.ForeignKey("users.id"))

    image_path = db.Column(db.String)
    is_detected = db.Column(db.Boolean, default=False)
    created_at = db.Column(db.DateTime, default=datetime.now)
    updated_at = db.Column(
        db.DateTime, default=datetime.now, onupdate=datetime.now
    )

flaskbook/apps/detector/__init__.py
import apps.detector.models

flaskbook/apps/detector/views.py
from apps.app import db
from apps.crud.models import User
from apps.detector.models import UserImage


from flask import Blueprint, render_template


dt = Blueprint("detector", __name__, template_folder="templates")

@dt.route('/')
def index():
    user_images =(
        db.session.query(User, UserImage)
        .join(UserImage)
        .filter(User.id == UserImage.user_id)
        .all()
    )
    return render_template("detector/index.html", user_images=user_images)

flaskbook/apps/detector/templates/detector/base.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8" />
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}"
    />
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"
    />
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand " href="{{ url_for('detector.index') }}"
                    >detector</a>
                <ul class="navbar-nav">
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <span class="nav-link">{{ current_user.username }}</span>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('auth.logout') }}" class="nav-link">로그아웃
                        </a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.signup') }}">신규등록
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login') }}">로그인</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        <section class="container">
        {% block content %}{% endblock %}
        </section>
    </body>
</html>

flaskbook/apps/detector/templates/detector/index.html
{% extends "detector/base.html" %}
{% block content %}
{% for user_image in user_images %}
<div class="card col-md-7 dt-image-content">
    <section>
        <img src="{{ user_image.UserImage.image_url }}" alt="이미지" />
    </section>
</div>
{% endfor %}
{% endblock %}